/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "NBioAPI.h"
/* Header for class NBioBSPJNI */

#ifndef _Included_NBioBSPJNI
#define _Included_NBioBSPJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NBioBSPJNI
 * Method:    sayHello
 * Signature: ()V
 */


JNIEXPORT NBioAPI_RETURN JNICALL Java_NBioBSPJNI_NBioBSPJNI_NativeOpenDevice
    (JNIEnv *env, jobject thisObj);

JNIEXPORT void JNICALL Java_NBioBSPJNI_NBioBSPJNI_NativeCapture
    (JNIEnv *env, jobject thisObj,jobject fir_handle);

    JNIEXPORT void JNICALL Java_NBioBSPJNI_NBioBSPJNI_TesteObject
   (JNIEnv *env, jobject thisObj, jobject iLevel);



JNIEXPORT NBioAPI_RETURN JNICALL Java_NBioBSPJNI_NBioBSPJNI_NativeVerify
    (JNIEnv *env,jobject thisObj, NBioAPI_HANDLE_PTR hHandle,  NBioAPI_FIR_HANDLE_PTR piStoredTemplate,
     NBioAPI_BOOL* pbResult,NBioAPI_FIR_PAYLOAD_PTR pPayload, NBioAPI_FIR_HANDLE_PTR  phAuditData,  NBioAPI_WINDOW_OPTION_PTR pWindowOption);


    JNIEXPORT NBioAPI_RETURN JNICALL Java_NBioBSPJNI_NBioBSPJNI_NativeVerify2
    (JNIEnv *env,jobject thisObj, NBioAPI_FIR_HANDLE hHandle, jstring *strin);

      JNIEXPORT void JNICALL Java_NBioBSPJNI_NBioBSPJNI_NativeVerifyMatch
  (JNIEnv *env, jobject thisObj, NBioAPI_HANDLE *param1, NBioAPI_FIR_HANDLE param2,  NBioAPI_INPUT_FIR param3,  NBioAPI_FIR_PAYLOAD_PTR *param4);




#ifdef __cplusplus
}
#endif
#endif
