/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "NBioAPI.h"
/* Header for class NBioBSPJNI */

#ifndef _Included_NBioBSPJNI
#define _Included_NBioBSPJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NBioBSPJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NBioBSPJNI_NBioBSPJNI_capture
  (JNIEnv *env, jobject thisObj, NBioAPI_FIR_HANDLE param1);

JNIEXPORT NBioAPI_RETURN JNICALL Java_NBioBSPJNI_NBioBSPJNI_NativeOpenDevice
  (JNIEnv *env, jobject thisObj);

#ifdef __cplusplus
}
#endif
#endif
